### ISSUE TITLE
Improve web design styling of NHL maintenance popup

### ISSUE THREAD

**Issue by smagara** [smagara/AgilitySports_web#34]
Current design is too vanilla and doesn't confirm to the overall web styling, also it lacks pizzaz

![Image](https://github.com/user-attachments/assets/bb422bb7-5705-4162-9ab7-bf08ce8658ed)

**Comment by ErnestoPozzo** [comment]
Can I work on this?

**Comment by smagara** [comment]
> Can I work on this?

Sorry Ernesto, didn't see this until now.  I'll create an item for the NBA Roster for similar treatment, and you can use this PR as a guide if you're still interested.

**Comment by smagara** [comment]
Pushed PR, screen looks much improved and more useable.

![Image](https://github.com/user-attachments/assets/b99f372d-da15-4eff-be03-431a55bcbb1e)

![Image](https://github.com/user-attachments/assets/4ebc50e4-332d-4882-a1e1-20032911ca4e)
